import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils"
import { Providers } from "@/components/providers";
import { ThemeToggle } from "@/components/theme-toggle";

const fontSans = FontSans({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body 
        className={cn(
          "min-h-screen bg-emerald-700 font-sans antialiased",
          fontSans.variable
        )}
      >
        <Providers
          attribute="class"
          defaultTheme="systems"
          enableSystem={true}
          disableTransitionOnChange
        >
          <div className="">
            <ThemeToggle />
          </div>
          {children}
        </Providers>
      </body>
    </html>
  );
}
